version: '3.7'

services:
  zep:
    image: zepai/zep:latest
    ports:
      - "8000:8000"
    volumes:
      - ./zep.yaml:/app/zep.yaml
    environment:
      - ZEP_CONFIG_FILE=zep.yaml
    networks:
      - minha_rede  # Conectar a la red existente "minha_rede"
    depends_on:
      - graphiti
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zep.rule=Host(`zep.agencybts.com`)"  # Cambia esto al dominio correcto
      - "traefik.http.services.zep.loadbalancer.server.port=8000"  # Puerto interno
      - "traefik.http.routers.zep.entrypoints=web"  # Para HTTP (puerto 80)
      # Si usas HTTPS:
      # - "traefik.http.routers.zep.entrypoints=websecure"
      # - "traefik.http.routers.zep.tls=true"
      # - "traefik.http.routers.zep.tls.certresolver=http"  # Let's Encrypt
    restart: always

  db:
    image: ankane/pgvector:v0.5.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - minha_rede  # Conectar a la red existente "minha_rede"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - zep-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  graphiti:
    image: zepai/graphiti:0.3
    ports:
      - "8003:8003"
    env_file:
      - .env
    networks:
      - minha_rede  # Conectar a la red existente "minha_rede"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8003/healthcheck')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - neo4j
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=gpt-4o-mini
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=zepzepzep
      - PORT=8003

  neo4j:
    image: neo4j:5.22.0
    networks:
      - minha_rede  # Conectar a la red existente "minha_rede"
    healthcheck:
      test: wget http://localhost:7687 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/zepzepzep

volumes:
  neo4j_data:
  zep-db:

networks:
  minha_rede:
    external: true  # Conexión con la red existente "minha_rede"
